services:
  - type: web
    name: n8n
    runtime: docker
    branch: main
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile.n8n
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "yourpassword"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: PORT
        value: "80"

  - type: web
    name: short-video-maker
    runtime: image
    region: frankfurt
    plan: free
    image:
      url: gyoridavid/short-video-maker:latest-tiny
    envVars:
      - key: PEXELS_API_KEY
        value: "iSX6vtduQKe3bLWBd0V"
      - key: PORT
        value: "3123"
    healthCheckPath: /
