services:
  - type: web
    name: n8n
    runtime: docker
    branch: main
    region: frankfurt
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "yourpassword"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: PORT
        value: "5678"
    image:
      dockerfilePath: Dockerfile.n8n
    repo: https://github.com/islammig200/n8n-video-auto

  - type: web
    name: short-video-maker
    runtime: image
    branch: main
    region: frankfurt
    plan: free
    envVars:
      - key: PEXELS_API_KEY
        value: "iSX6vtduQKe3bLWBd0V"
    image:
      name: gyoridavid/short-video-maker:latest-tiny
